[package]
name = "tarantool-rust-tutorial"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tarantool = "0.4"
serde = "1.0"

[lib]
name = "procedures"
crate-type = ["cdylib"]
